Update XB to latest dev version.

diff --git a/web/modules/custom/experience_builder/.gitlab-ci.yml b/web/modules/custom/experience_builder/.gitlab-ci.yml
--- a/web/modules/custom/experience_builder/.gitlab-ci.yml
+++ b/web/modules/custom/experience_builder/.gitlab-ci.yml
@@ -46,6 +46,9 @@ include:
       # - "/includes/include.drupalci.main-d7.yml"
       - "/includes/include.drupalci.variables.yml"
       - "/includes/include.drupalci.workflows.yml"
+  # Local includes
+  - local: .gitlab/ci/drupal.yml
+  - local: .gitlab/ci/test.yml
 
 stages:
   - development
@@ -81,10 +84,6 @@ variables:
   CI_PARENT_PROJECT_NAME: experience_builder
   PHPUNIT_FAIL_ON_PHPUNIT_DEPRECATION: 0
   _CONCURRENCY_THREADS: '12'
-
-# This module wants to strictly comply with Drupal core's word use standards.
-cspell:
-  allow_failure: false
 
 # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
 .is-push-rule: &is-push-rule
@@ -138,108 +137,22 @@ cspell:
       - ui/tests/fixtures/**/*
     when: on_success
 
-.CLI-files-change-rule: &CLI-files-change-rule
-  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-    changes:
-      - cli/package.json
-      - cli/**/*.js
-      - cli/**/*.ts
-      - cli/**/*.tsx
-      - cli/tsconfig.json
+# Disable jobs from the upstream template.
+phpcs:
+  rules:
+    - when: never
 
-.CLI-HTTP-API-change-rule: &CLI-HTTP-API-change-rule
-  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-    changes:
-      - openapi.yml
-      - src/Entity/JavaScriptComponent.php
-      - src/Controller/ApiConfigControllers.php
+phpstan:
+  rules:
+    - when: never
 
-# Helper to setup a Drupal installation
-#
-# This should be quite fast with a warm cache, and is only used by one job
-# at the moment, so not currently worth the overhead of saving the output as
-# an artifact and starting a new job based on it.
-#
-# The drupal.org composer template creates a web/ directory and then
-# individually symlinks all the project files into module directory.
-# This causes some very strange behavior and node.js scripts will refuse to
-# run in a lot of cases, so this is an alternative job.
-.drupal: &drupal
-  # Move everything into a subdirectory
-  - mkdir tmp
-  - find . -maxdepth 1 -type f -not -path "./tmp*" -exec mv {} tmp/ \;
-  - find . -maxdepth 1 -type d -not -path "." -not -path "./tmp" -exec mv {} tmp/ \;
-  - mv tmp $CI_PROJECT_NAME
-  # Get Drupal
-  - composer create-project drupal/recommended-project:$DRUPAL_CORE _drupal
-  - cd _drupal
-  # Add core-dev, Experience Builder, and drush
-  - |
-    composer config repositories.$CI_PARENT_PROJECT_NAME --json '{"type": "path", "url": "../'$CI_PROJECT_NAME'", "options": { "symlink": false } }'
-  - composer config minimum-stability dev
-  - composer require drupal/core-dev "drupal/$CI_PARENT_PROJECT_NAME @dev" drush/drush --with-all-dependencies
-  - |
-    PACKAGE_INFO=$(composer info drupal/$CI_PARENT_PROJECT_NAME --all | grep "^dist" | awk -F": " "{print \$2}")
-    EXPECTED_PATH="[path] ../$CI_PROJECT_NAME $CI_COMMIT_SHA"
-    if [ "$PACKAGE_INFO" != "$EXPECTED_PATH" ]; then
-      echo "Unable to link to local $CI_PARENT_PROJECT_NAME package"
-      echo "Expected: $EXPECTED_PATH"
-      echo "Got: $PACKAGE_INFO"
-      exit 1
-    fi
-  # Setup webserver root
-  - rm -rf /var/www/html
-  - ln -s $CI_PROJECT_DIR/_drupal/web /var/www/html
-  - chown -R www-data:www-data /var/www/html
-  - chown -R www-data:www-data $CI_PROJECT_DIR/_drupal
-  # Setup directories
-  - chmod 777 $CI_PROJECT_DIR/_drupal/web/sites
-  - mkdir -p $CI_PROJECT_DIR/_drupal/web/sites/simpletest
-  - chmod 777 $CI_PROJECT_DIR/_drupal/web/sites/simpletest
-  - mkdir -p $CI_PROJECT_DIR/_drupal/web/sites/default/files
-  - chmod 777 $CI_PROJECT_DIR/_drupal/web/sites/default/files
-  # Start the webserver
-  - service apache2 start
-  # Set simpletest environment variables
-  - !reference [ .simpletest-db ]
-  - !reference [ .show-environment-variables ]
-  # Ensure that every test site will be able to discover and install test modules.
-  # Anything in settings.testing.php is automatically copied into the settings of
-  # individual test sites. See \Drupal\Core\Test\FunctionalTestSetupTrait::prepareSettings(),
-  # which is called (indirectly) by \Drupal\TestSite\Commands\TestSiteInstallCommand.
-  - cd $CI_PROJECT_DIR/_drupal/web/sites/default
-  - echo '<?php' >> settings.testing.php
-  - echo '$settings["extension_discovery_scan_tests"] = TRUE;' >> settings.testing.php
-  # Change to the project directory
-  - cd $CI_PROJECT_DIR/_drupal/web/modules/contrib/$CI_PARENT_PROJECT_NAME
-  # Install the UI
-  # @todo consolidate this with the UI job?
-  - cd ui
-  - npm ci
-  - npm run build
-  - cd ../
+cspell:
+  rules:
+    - when: never
 
-# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
 composer-lint:
   rules:
-    - *is-push-rule
-    - *php-files-change-rule
-    - changes:
-        - composer.json
-      when: on_success
-    - *manual-rule
-
-phpcs:
-  allow_failure: false
-  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
-  rules:
-    - *is-push-rule
-    - *php-files-change-rule
-    # Also run whenever we catch up to the upstream PHPCS rules.
-    - changes:
-        - core.phpcs.xml.dist
-      when: on_success
-    - *manual-rule
+    - when: never
 
 phpcs-rules-match-drupal-11:
   stage: development
@@ -296,15 +209,6 @@ stylelint:
     reports:
       codequality: gl-codequality.json
 
-# This module wants to strictly comply with PHPStan.
-.phpstan-base:
-  allow_failure: false
-  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
-  rules:
-    - *is-push-rule
-    - *php-files-change-rule
-    - *manual-rule
-
 phpunit:
   variables:
     # Note: XB uses `@group #slow` to start slow tests early. The threshold is (at the time of writing) ~60 seconds.
@@ -352,7 +256,7 @@ eslint:
   # This module wants to strictly comply with eslint.
   allow_failure: false
   before_script:
-    # 🤷‍.eslintignore already instructs eslint to ignore this, but it does not seem to work. This is validated by the `UI eslint` and `CLI eslint` jobs below.
+    # 🤷‍.eslintignore already instructs eslint to ignore this, but it does not seem to work. This is validated by the `UI eslint` job below.
     - rm -rf ui
     - rm -rf tests/src/Playwright playwright.config.ts eslint.config.mjs
   # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
@@ -414,69 +318,6 @@ UI eslint:
     reports:
       junit: ui-eslint-junit.xml
 
-CLI:
-  stage: build
-  image: node:20-alpine
-  needs: []
-  rules:
-    - *is-push-rule
-    - *CLI-files-change-rule
-    - *CLI-HTTP-API-change-rule
-    - *manual-rule
-  script:
-    - cd cli
-    - npm ci
-    - npm run build
-
-CLI eslint:
-  stage: validate
-  image: node:20-alpine
-  allow_failure: false
-  needs:
-    - CLI
-  rules:
-    - *is-push-rule
-    - *CLI-files-change-rule
-    - *manual-rule
-  script:
-    - cd cli
-    - npm ci
-    - npx eslint --format=junit --output-file=$CI_PROJECT_DIR/cli-eslint-junit.xml --max-warnings=0
-  artifacts:
-    expose_as: junit
-    expire_in: 6 mos
-    when: always
-    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
-    paths:
-      - cli-eslint-junit.xml
-    reports:
-      junit: cli-eslint-junit.xml
-
-CLI vitest:
-  stage: test
-  image: node:20-alpine
-  allow_failure: false
-  needs:
-    - CLI
-  rules:
-    - *is-push-rule
-    - *CLI-files-change-rule
-    - *CLI-HTTP-API-change-rule
-    - *manual-rule
-  script:
-    - cd cli
-    - npm ci
-    - npm test -- --reporter=junit --outputFile=$CI_PROJECT_DIR/cli-vitest-junit.xml
-  artifacts:
-    expose_as: junit
-    expire_in: 6 mos
-    when: always
-    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
-    paths:
-      - cli-vitest-junit.xml
-    reports:
-      junit: cli-vitest-junit.xml
-
 vitest:
   stage: test
   image: node:20-alpine
@@ -516,7 +357,10 @@ vitest:
   before_script:
     - echo -e "\e[0Ksection_start:`date +%s`:Cypress-deps[collapsed=true]\r\e[0KInstall Cypress dependencies."
     - sudo apt-get -y update
-    - sudo apt-get -y install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
+    - sudo apt-get -y install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb alsa-utils pulseaudio
+    - echo "pcm.!default { type pulse }" > ~/.asoundrc
+    - echo "ctl.!default { type pulse }" >> ~/.asoundrc
+    - pulseaudio --system --disallow-exit --disallow-module-loading &
     - echo -e "\e[0Ksection_end:`date +%s`:Cypress-deps\r\e[0K"
     #
     # Copied from `.nightwatch-base`, but converted to use GitLab CI references.
@@ -606,6 +450,53 @@ cypress unit:
     paths:
       - "docs/diagrams/*.md"
 
+lint (php):
+  stage: validate
+  needs: []
+  image: justafish/drupalci-environments-playwright:latest
+  variables:
+    GIT_DEPTH: 1
+    COMPOSER_ROOT_VERSION: 0.0.0
+  before_script:
+    - !reference [ .drupal-files ]
+    - composer run install-dev-deps
+    - mkdir -p test-results
+  script:
+    # PHPStan doesn't allow multiple outputs, but it will cache the result so
+    # the second run is very fast.
+    - composer run phpstan -- --error-format=junit > test-results/phpstan.xml || true
+    - !reference [ .test_runner ]
+    - run_test "composer validate" "composer validate --strict"
+    - run_test "phpcs" "composer run phpcs"
+    - run_test "phpstan" "composer run phpstan"
+    - !reference [ .test_summary ]
+  after_script:
+    - cp -R _drupal/web/modules/contrib/$CI_PARENT_PROJECT_NAME/test-results $CI_PROJECT_DIR/test-results
+  artifacts:
+    expose_as: 'Static tests report'
+    when: always
+    expire_in: 6 mos
+    paths:
+      - test-results/
+    reports:
+      junit:
+        - test-results/phpcs.xml
+        - test-results/phpstan.xml
+
+# This is the lint job for packages that are under the root package.json and
+# workspace.
+# @todo migrate the ui/ packages to the top level workspace now that we can get
+# around the GitLab issues.
+lint (node):
+  stage: validate
+  needs: []
+  image: justafish/drupalci-environments-playwright:latest
+  before_script:
+    - . /root/.nvm/nvm.sh && nvm install 24 && nvm alias default 24
+  script:
+    - npm ci
+    - npm run lint
+
 playwright:
   stage: test
   needs: []
@@ -633,9 +524,10 @@ playwright:
     DRUPAL_TEST_PLAYWRIGHT_SKIP_TEARDOWN: true
   before_script:
     - !reference [ .drupal ]
+    - composer run install-dev-deps
   script:
-    - npm install
-    - npx npm-run-all --continue-on-error --parallel test:playwright
+    - npm ci
+    - npm run test:playwright
   after_script:
     - mkdir -p $CI_PROJECT_DIR/logs
     - cp -R /var/log/apache2 $CI_PROJECT_DIR/logs/apache2
@@ -654,22 +546,56 @@ playwright:
       junit:
         - test-results/playwright.xml
 
-playwright code style:
-  stage: validate
+CLI Test:
+  stage: test
   image: node:20-alpine
-  allow_failure: false
   needs: []
   rules:
-    - *is-push-rule
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-      changes:
-        - tests/src/Playwright/*
-        - tests/src/Playwright/**/*
-    - *manual-rule
+    - changes:
+        - "cli/**/*"
+        - package.json
+        - package-lock.json
+        - openapi.yml
+        - src/Entity/JavaScriptComponent.php
+        - src/Controller/ApiConfigControllers.php
+        - .gitlab-ci.yml
+    - if: '$CI_COMMIT_TAG =~ /^cli-\d+\.\d+\.\d+(-\w+\d*)?$/'
+  before_script:
+    mkdir -p test-results
+  # This job must pass, but must also not disrupt XB's CI if dependencies have a security vulnerability.
+  allow_failure:
+    exit_codes:
+      # `npm audit …` fails (implies upstream security vulnerability that may or may not affect XB)
+      - 100
   script:
     - npm ci
-    - npm run test:eslint
-    - npm run test:prettier
+    - npm run test --workspace=cli
+    - npm run build --workspace=cli
+    - npm version 0.0.1 --workspace=cli
+    - npm pack --pack-destination=test-results --workspace=cli
+    - npm audit --audit-level=moderate --production || exit 100
+  artifacts:
+    expose_as: 'CLI package'
+    when: always
+    expire_in: 6 mos
+    paths:
+      - test-results/
+
+CLI Publish:
+  stage: publish
+  image: node:20-alpine
+  needs:
+    - lint (node)
+    - CLI Test
+  rules:
+    - if: '$CI_COMMIT_TAG =~ /^cli-\d+\.\d+\.\d+(-\w+\d*)?$/'
+  before_script:
+    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
+  script:
+    - npm ci
+    - npm run build --workspace=cli
+    - npm version $(echo ${CI_COMMIT_TAG} | cut -c5-) --workspace=cli
+    - npm publish --access public --workspace=cli
 
 # User facing documentation.
 pages-mr:
